apiVersion : apps/v1
kind: Deployment
metadata:
  name: revaturecinephiliacsuserrepo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revaturecinephiliacsuserrepo
  template:
    metadata:
      labels:
        app: revaturecinephiliacsuserrepo 
    spec:
      containers:
        - name: revaturecinephiliacsuserrepo 
          image: 03012021batchp3acr.azurecr.io/revaturecinephiliacsuserrepo
          ports:
          - containerPort: 80